<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static create(array $array)
 * @method static where(string $string, string $string1)
 */
class Menu extends Model
{
    use HasFactory;

    protected $fillable = [
        'site',
        'name',
        'slug',
        'bg_color',
        'status',
        'created_by',
        'updated_by',
    ];

    public function menuItems(){
        return $this->hasMany(MenuItem::class);
    }

    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }
    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    public function scopeStatus($query)
    {
        return $query->where('status', 1);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($menu) {
            $menu->slug = slug($menu->name);
            $menu->created_by = Auth::id() ?? 1;
            $menu->updated_by = Auth::id() ?? 1;
        });
        static::updating(function ($menu) {
            $menu->slug = slug($menu->name);
            $menu->updated_by = Auth::id();
        });
    }
}
